lib/chit_chat_en_web/router.ex
defmodule ChitChatEnWeb.Router do
  use ChitChatEnWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug ChitChatEn.Auth
    plug :put_user_token
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ChitChatEnWeb do
    pipe_through [:browser]

    get "/", PageController, :index
    get "/login", SessionController, :new
    get "/logout", SessionController, :delete
    resources("/rooms", RoomController)
    resources("/users", UserController)
    resources("/sessions", SessionController, only: [:new, :create, :delete], singleton: true)
  end

  # Other scopes may use custom stacks.
  # scope "/api", ChitChatEnWeb do
  #   pipe_through :api
  # end
  defp put_user_token(conn, _) do
    if current_user = conn.assigns[:current_user] do
      user_id_token = Phoenix.Token.sign(conn, "user_id", current_user.id)
      assign(conn, :user_id, user_id_token)
    else
      conn
    end
  end
end

lib/chit_chat_en_web/views/layout_view.ex
defmodule ChitChatEnWeb.LayoutView do
  use ChitChatEnWeb, :view
end

lib/chit_chat_en_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Chatting System</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <ul>
            <%= if @current_user do %>
              <li><%= link @current_user.name, to: Routes.user_path(@conn, :show, @current_user.id) %></li>
              <li><%= link "Log out", to: Routes.session_path(@conn, :delete) %></li>
            <% else %>
              <li><%= link "Register", to: Routes.user_path(@conn, :new) %></li>
              <li><%= link "Log In", to: Routes.session_path(@conn, :new) %></li>
            <% end %>
          </ul>
        </nav>
        <a href="http://localhost:4000" >
          <img src="https://img.icons8.com/doodle/50/000000/chat.png" alt="Logo"/>
        </a>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script>window.userToken = "<%= assigns[:user_id] %>";</script>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>