lib/chit_chat_en_web/router.ex
defmodule ChitChatEnWeb.Router do
  use ChitChatEnWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug ChitChatEn.Auth
    plug :put_user_token
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ChitChatEnWeb do
    pipe_through [:browser]

    get "/", PageController, :index
    get "/login", SessionController, :new
    get "/logout", SessionController, :delete
    resources("/rooms", RoomController)
    resources("/users", UserController)
    resources("/sessions", SessionController, only: [:new, :create, :delete], singleton: true)
  end

  # Other scopes may use custom stacks.
  # scope "/api", ChitChatEnWeb do
  #   pipe_through :api
  # end
  defp put_user_token(conn, _) do
    if current_user = conn.assigns[:current_user] do
      user_id_token = Phoenix.Token.sign(conn, "user_id", current_user.id)
      assign(conn, :user_id, user_id_token)
    else
      conn
    end
  end
end

lib/chit_chat_en/accounts/user.ex
defmodule ChitChatEn.Accounts.User do
  use Ecto.Schema
  import Ecto.Changeset

  schema "users" do
    field :name, :string
    field :username, :string
    has_one :credential, ChitChatEn.Accounts.Credential

    timestamps()
  end

  @doc false
  def changeset(user, attrs) do
    user
    |> cast(attrs, [:name, :username])
    |> validate_required([:name, :username])
    |> unique_constraint(:username)
  end
end

lib/chit_chat_en_web/controllers/user_controller.ex
defmodule ChitChatEnWeb.UserController do
  use ChitChatEnWeb, :controller

  alias ChitChatEn.Accounts
  alias ChitChatEn.Accounts.User
  plug :logged_in_user when action not in [:new, :create]
  plug :correct_user when action in [:edit, :update, :delete]
  plug :admin_user when action in [:index, :delete]

  def index(conn, _params) do
    users = Accounts.list_users()
    render(conn, "index.html", users: users)
  end

  def new(conn, _params) do
    changeset = Accounts.change_user(%User{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"user" => user_params}) do
    case Accounts.create_user(user_params) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "User created successfully.")
        |> redirect(to: Routes.user_path(conn, :show, user))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    user = Accounts.get_user!(id)
    render(conn, "show.html", user: user)
  end

  def edit(conn, %{"id" => id}) do
    user = Accounts.get_user!(id)
    changeset = Accounts.change_user(user)
    render(conn, "edit.html", user: user, changeset: changeset)
  end

  def update(conn, %{"id" => id, "user" => user_params}) do
    user = Accounts.get_user!(id)

    case Accounts.update_user(user, user_params) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "User updated successfully.")
        |> redirect(to: Routes.user_path(conn, :show, user))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", user: user, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    user = Accounts.get_user!(id)
    {:ok, _user} = Accounts.delete_user(user)

    conn
    |> put_flash(:info, "User deleted successfully.")
    |> redirect(to: Routes.user_path(conn, :index))
  end

  defp correct_user(
         %{assigns: %{current_user: current, admin_user: admin}, params: %{"id" => id}} = conn,
         _params
       ) do
    if String.to_integer(id) == current.id || admin do
      conn
    else
      conn
      |> put_flash(:error, "You don't have access to that page")
      |> redirect(to: Routes.user_path(conn, :show, current))
      |> halt()
    end
  end
end

lib/chit_chat_en_web/views/user_view.ex
defmodule ChitChatEnWeb.UserView do
  use ChitChatEnWeb, :view
end

lib/chit_chat_en_web/templates/user/edit.html.eex
<h1>Edit User</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.user_path(@conn, :update, @user)) %>

<span><%= link "Back", to: Routes.user_path(@conn, :index) %></span>

lib/chit_chat_en_web/templates/user/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :name %>
  <%= text_input f, :name %>
  <%= error_tag f, :name %>

  <%= label f, :username %>
  <%= text_input f, :username %>
  <%= error_tag f, :username %>

  <div class="form-group">
   <%= inputs_for f, :credential, fn cf -> %>
    <%= label cf, :email %>
    <%= text_input cf, :email %>
    <%= error_tag cf, :email %>

    <%= label cf, :password %>
    <%= password_input cf, :password %>
    <%= error_tag cf, :password %>

    <%= label cf, :password_confirmation %>
    <%= password_input cf, :password_confirmation %>
    <%= error_tag cf, :password_confirmation %>
   <%end%>
  </div>

  <div>
    <%= submit "Save" %>
  </div>
<% end %>

lib/chit_chat_en_web/templates/user/index.html.eex
<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Username</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for user <- @users do %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.username %></td>

      <td>
        <span><%= link "Show", to: Routes.user_path(@conn, :show, user) %></span>
        <span><%= link "Edit", to: Routes.user_path(@conn, :edit, user) %></span>
        <span><%= link "Delete", to: Routes.user_path(@conn, :delete, user), method: :delete, data: [confirm: "Are you sure?"] %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New User", to: Routes.user_path(@conn, :new) %></span>

lib/chit_chat_en_web/templates/user/new.html.eex
<h1>New User</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.user_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.user_path(@conn, :index) %></span>

lib/chit_chat_en_web/templates/user/show.html.eex
<h1>Show User</h1>

<ul>

  <li>
    <strong>Name:</strong>
    <%= @user.name %>
  </li>

  <li>
    <strong>Username:</strong>
    <%= @user.username %>
  </li>

</ul>

<span><%= link "Edit", to: Routes.user_path(@conn, :edit, @user) %></span>
<span><%= link "Back", to: Routes.user_path(@conn, :index) %></span>
<span><%= link "Room", to: Routes.room_path(@conn, :index) %></span>